In [1]:
# Array manipulation
import numpy as np

# Random variables generator
import random as rand

# data processing / .csv manipulation and reading
import pandas as pd


# Data visualization
import seaborn as sns
%matplotlib inline
from matplotlib import pyplot as plt
from matplotlib import style

# Algorithms / AI
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth, association_rules

In [2]:
from auxModule import group_map

In [3]:
len(group_map.keys())

24

In [4]:
raw_data = pd.read_excel('../Base_MUNIC_2020.xlsx', sheet_name='Gestão de riscos') # Objects are loaded with infos from .csv

c:\Users\tobie\.conda\envs\COPE\Lib\site-packages\openpyxl\packaging\core.py:99: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.datetime.utcnow()
c:\Users\tobie\.conda\envs\COPE\Lib\site-packages\openpyxl\packaging\core.py:99: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.datetime.utcnow()

In [5]:
data = raw_data[:]

In [6]:
# Let's drop the columns 'CodMun', 'UF' and 'Mun'

data.drop('CodMun', axis='columns', inplace=True)
data.drop('Cod UF', axis='columns', inplace=True)
data.drop('Mgrd09', axis='columns', inplace=True)
data.drop('Mgrd1011', axis='columns', inplace=True)
data.drop('Mgrd1021', axis='columns', inplace=True)

C:\Users\tobie\AppData\Local\Temp\ipykernel_32860\14388751.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('CodMun', axis='columns', inplace=True)
C:\Users\tobie\AppData\Local\Temp\ipykernel_32860\14388751.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('Cod UF', axis='columns', inplace=True)
C:\Users\tobie\AppData\Local\Temp\ipykernel_32860\14388751.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('Mgrd09', axis='columns', inplace=True)
C:\Users\tobie\AppData\Local\Temp\ipykernel_32860\14388751.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('Mgrd1011', axis='columns', inplace=True)
C:\Users\tobie\AppData\Local\Temp\ipykernel_32860\14388751.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('Mgrd1021', axis='columns', inplace=True)

In [7]:
# I need to adapt this dataset so that I can analyse it using the AI.
# The data is using binary inputs in order to track the occurrences of
# risk management measures, so I have to replace all 'Yes's with the name
# of the column and delete the options with 'No' or '-'.

relation_dataset = []

for mun_index, municipality in enumerate(data.values): # For every municipality
    
    relation_dataset.append(list()) # Allocate the municipality space in memory 
    
    for att_index, attribute in enumerate(municipality): # For every attribute
        
        this_att_name = data.columns[att_index] # Take the att name
        
        if attribute == 'Sim': # If the attribute is existent
            relation_dataset[mun_index].append(this_att_name) # Add to the new dataset
        
        elif (attribute != 'Não') and (attribute != '-') and (attribute != 'Não sabe') and (attribute != 'Recusa') and (type(attribute) is not int): # If isn't binary
            relation_dataset[mun_index].append(attribute) # Register att the new dataset

relation_dataset[100]

['AM',
 'Ipixuna',
 '4 - 20001 até 50000',
 '1 - Norte',
 'Mgrd01',
 'Mgrd031',
 'Mgrd032',
 'Mgrd035',
 'Mgrd042',
 'Mgrd044',
 'Mgrd05',
 'Mgrd06',
 'Mgrd07',
 'Mgrd08',
 'Mgrd101',
 'Mgrd102',
 'Mgrd103',
 'Urbana e rural',
 'Mgrd1041',
 'Mgrd1044',
 'Mgrd10511',
 'Mgrd1710',
 'Mgrd181',
 'Mgrd187',
 'Mgrd19',
 'Mgrd208',
 'Mgrd212',
 'Mgrd214',
 'Mgrd221',
 'Mgrd227',
 'Mgrd229',
 'Mgrd2211',
 'Mgrd238']

In [8]:
import auxModule

main_dataset = auxModule.GroupedAttDataset()

main_dataset.add_user_list_from_scratch(relation_dataset)

In [9]:
main_dataset.commit_dataframe()

In [10]:
print(main_dataset.dframe.shape)
main_dataset.filter_dframe( 0.5 )
print(main_dataset.dframe.shape, '\n')
main_dataset.commit_users()

(5570, 24)
(5570, 13)

In [11]:
main_dataset.dframe

,Atingido_Alagamentos,Atingido_Des,Atingido_Enchente,Atingido_Enxurrada,Nao_ATV_P&DC,Nao_Instr_Inundacao,Nao_Medida_Estrutural_RRD,Nao_RR_Seca,Nao_Red_Des,Nao_Red_Enchente,Nao_Red_Enxurrada,Tem_Instr_Deslizamento,Tem_Red_Des
0,0,0,1,0,1,0,0,0,0,0,0,0,0
1,1,0,1,1,0,0,0,0,0,0,1,1,1
2,0,1,1,1,0,1,0,0,1,1,1,0,0
3,1,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,0,0,0,0,0,0,0,0,0,0,0,0,0
5566,0,0,0,0,0,1,0,0,0,0,0,0,0
5567,0,0,0,0,1,1,1,0,0,0,0,0,0
5568,0,0,0,1,0,0,0,0,0,0,1,1,0
5569,1,0,1,1,0,0,0,0,0,0,0,1,1

In [12]:
main_dataset.dframe.insert(0, "Mun", raw_data['Mun'], True)
main_dataset.dframe.insert(1, "UF", raw_data['UF'], True)

In [17]:
len(main_dataset.dframe.columns)
main_dataset.dframe

,Mun,UF,Atingido_Alagamentos,Atingido_Des,Atingido_Enchente,Atingido_Enxurrada,Nao_ATV_P&DC,Nao_Instr_Inundacao,Nao_Medida_Estrutural_RRD,Nao_RR_Seca,Nao_Red_Des,Nao_Red_Enchente,Nao_Red_Enxurrada,Tem_Instr_Deslizamento,Tem_Red_Des
0,Alta Floresta DOeste,RO,0,0,1,0,1,0,0,0,0,0,0,0,0
1,Ariquemes,RO,1,0,1,1,0,0,0,0,0,0,1,1,1
2,Cabixi,RO,0,1,1,1,0,1,0,0,1,1,1,0,0
3,Cacoal,RO,1,0,1,0,0,0,0,0,0,0,0,0,0
4,Cerejeiras,RO,0,0,0,0,0,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,Vianópolis,GO,0,0,0,0,0,0,0,0,0,0,0,0,0
5566,Vicentinópolis,GO,0,0,0,0,0,1,0,0,0,0,0,0,0
5567,Vila Boa,GO,0,0,0,0,1,1,1,0,0,0,0,0,0
5568,Vila Propício,GO,0,0,0,1,0,0,0,0,0,0,1,1,0
5569,Brasília,DF,1,0,1,1,0,0,0,0,0,0,0,1,1

In [18]:
filename = f'generated/base_brasil/base_brasil_mun'
with open(filename+'.csv', 'w') as output_handle: # Save as .csv for visualization
    main_dataset.dframe.to_csv(filename+'.csv')
with open(filename+'.xlsx', 'w') as output_handle: # Save as .csv for visualization
    main_dataset.dframe.to_excel(filename+'.xlsx')

c:\Users\tobie\.conda\envs\COPE\Lib\site-packages\openpyxl\packaging\core.py:99: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.datetime.utcnow()
c:\Users\tobie\.conda\envs\COPE\Lib\site-packages\openpyxl\writer\excel.py:292: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  workbook.properties.modified = datetime.datetime.utcnow()